# encoding: UTF-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)



roles = Role.create([
    {:name=>'Reader'},
    {:name=>'Writer'},
    {:name=>'Sender'},
    {:name=>'Administrator'},
    {:name=>'Super-Administrator'},
 ])

waters = Water.create([
    {:name=>'Perikanan Laut'},
    {:name=>'Perikanan Perairan Umum'}
  ])

gear_categories = GearCategory.create([
    {:name=>'Pukat Tarik'},
    {:name=>'Pukat Kantong'},
    {:name=>'Pukat Cincin'},
    {:name=>'Jaring Insang'},
    {:name=>'Jaring Angkat'},
    {:name=>'Pancing'},
    {:name=>'Perangkap'},
    {:name=>'Alat Pengumpul dan Alat Penangkap'},
    {:name=>'Lain-lain'}
  ])
  
gear = Gear.create([
  {:name=>'Pukat tarik udang ganda', :gear_category_id=>"1"},
  {:name=>'Pukat tarik udang tunggal', :gear_category_id=>'1'},
  {:name=>'Pukat tarik berbingkai', :gear_category_id=>'1'},
  {:name=>'Pukat tarik ikan', :gear_category_id=>'1'},
  {:name=>'Payang (lampara)', :gear_category_id=>'2'},
  {:name=>'Dogol (lampara dasar,cantrang,jaring arad)', :gear_category_id=>'2'},
  {:name=>'Pukat pantai', :gear_category_id=>'2'},
  {:name=>'Pukat Cincin', :gear_category_id=>'3'},
  {:name=>'Jaring insang hanyut', :gear_category_id=>'4'},
  {:name=>'Jaring insang lingkar', :gear_category_id=>'4'},
  {:name=>'Jaring klitik', :gear_category_id=>'4'},
  {:name=>'Jaring insang tetap', :gear_category_id=>'4'},
  {:name=>'Jaring tiga lapis', :gear_category_id=>'4'},
  {:name=>'Bagan perahu rakit', :gear_category_id=>'5'},
  {:name=>'Bagan tancap', :gear_category_id=>'5'},
  {:name=>'Serok dan songko', :gear_category_id=>'5'},
  {:name=>'Anco', :gear_category_id=>'5'},
  {:name=>'Rawai tuna', :gear_category_id=>'6'},
  {:name=>'Rawai hanyut lain selain rawa tuna', :gear_category_id=>'6'},
  {:name=>'Rawai tetap', :gear_category_id=>'6'},
  {:name=>'Rawai tetap dasar', :gear_category_id=>'6'},
  {:name=>'Huhate', :gear_category_id=>'6'},
  {:name=>'Pancing tonda', :gear_category_id=>'6'},
  {:name=>'Pancing ulur	', :gear_category_id=>'6'},
  {:name=>'Pancing tegak', :gear_category_id=>'6'},
  {:name=>'Pancing cumi', :gear_category_id=>'6'},
  {:name=>'Pancing lainnya', :gear_category_id=>'6'},
  {:name=>'Sero (kelong)', :gear_category_id=>'7'},
  {:name=>'Jermal', :gear_category_id=>'7'},
  {:name=>'Bubu (bubu ambal)', :gear_category_id=>'7'},
  {:name=>'Perangkap lain', :gear_category_id=>'7'},
  {:name=>'Alat pengumpul rumput laut', :gear_category_id=>'8'},
  {:name=>'Alat penangkap kerang', :gear_category_id=>'8'},
  {:name=>'Alat penangkap teripang', :gear_category_id=>'8'},
  {:name=>'Alat penangkap kepiting', :gear_category_id=>'8'},
  {:name=>'Muroami', :gear_category_id=>'9'},
  {:name=>'Jala tebar', :gear_category_id=>'9'},
  {:name=>'Garpu, tombak, dll', :gear_category_id=>'9'},
  {:name=>'Jenis alat lainnya', :gear_category_id=>'9'},
  {:name=>'Jaring Perangkap', :gear_category_id => 4 }
  ])
  
  
offices =Office.create([
    {:name=>'PEMDA 3', :address1=>'JL. BELERANG1', :address2=>'JAKARTA BARAT',:address3=>'CONJKT3'},
    {:name=>'PEMDA 2', :address1=>'KOMP. DARMAGA 2', :address2=>'JAKARTA TIMUR', :address3=>'CONJKT2'},
    {:name=>'PEMDA 1', :address1=>'JL. KEPAHLAWANAN', :address2=>'JAKARTA UTARA', :address3=>'CONJKT1'},
    {:name=>'SYSTEM', :address1=>'SYSTEM', :address2=>'SYSTEM', :address3=>'SYSTEM'}
  ])
  
positions = Position.create([
    {:name=>'Ka. DIVISI PERKAPALAN'},
    {:name=>'Ka. BAGIAN KAPAL MOTOR '},
    {:name=>'Ka. UNIT PENGALENGAN 1'},
    {:name=>'Wka. BAGIAN DIVISI PERKAP'},
    {:name=>'ADMINISTRATOR'},
    {:name=>'TESTING'}
  ])
  
statuses = Status.create([
    {:name=>'Statistik Perikanan Tangkap'},
    {:name=>'Non Statistik Perikanan Tangkap'}
  ])
  
categories = Category.create([
    {:name=>'Demersal'},
    {:name=>'Pelagis Kecil'},
    {:name=>'Pelagis Besar'}
  ])
  
sectors = Sector.create([
    {:name=>'Ikan'},
    {:name=>'Udang-Udangan'},
    {:name=>'Bintang Berkulit Keras'},
    {:name=>'Bintang Berkulit Lunak'},
    {:name=>'Binatang Air Lainya'},
    {:name=>'Tumbuhan Air Lainnya'}
  ])
  
fish = Fish.create([
  {:code=>'IPL1.001', :nat_nm=>'Manyung', :loc_nm => '', :family => 'Ariidae', :eng_nm => 'Giant catfish', :lat_nm => 'Netuma thalassina (Rüppell, 1837)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.002', :nat_nm=>'Cendro, saku, Kacangan, Kajang, Loncong', :loc_nm => '', :family => 'Belonidae', :eng_nm => 'Needle fishes', :lat_nm => 'Belonidae/Tylosurus spp.', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.003', :nat_nm=>'Lolosi biru', :loc_nm => '', :family => 'Caesionidae', :eng_nm => 'Blue and gold fusilier', :lat_nm => 'Caesio caerulaurea (Lacepède, 1801)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.004', :nat_nm=>'Ekor kuning', :loc_nm => '', :family => 'Caesionidae', :eng_nm => 'Redbelly yellowtail fusilier', :lat_nm => 'Caesio cuning (Bloch, 1791)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.005', :nat_nm=>'Selar como', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Shrimp scad', :lat_nm => 'Alepes djeddaba (Forsskal, 1755)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.006', :nat_nm=>'Selar hijau', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Slender scaled scad', :lat_nm => 'Atule mate', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.007', :nat_nm=>'Kwee', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Bluefin trevally', :lat_nm => 'Caranx melampygus (Cuvier, 1833)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.008', :nat_nm=>'Kwee', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Bigeye trevally', :lat_nm => 'Caranx sexfaciatus (Quoy & Gaimard,1825)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.009', :nat_nm=>'Kwee', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Tille trevally', :lat_nm => 'Caranx tile (Cuvier, 1833)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.010', :nat_nm=>'Malalugis/Layang anggur', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Redtail scad', :lat_nm => 'Decapterus kurroides (Bleeker,1855)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.011', :nat_nm=>'Layang deles', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Shortfin scad', :lat_nm => 'Decapterus macrosoma (Bleeker, 1855)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.012', :nat_nm=>'Layang biru', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Mackerel scad', :lat_nm => 'Decapterus macarellus (Cuvier, 1833)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.013', :nat_nm=>'Layang, Benggol', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Slander scad', :lat_nm => 'Decapterus. Ruselli (Rüppell, 1830)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.014', :nat_nm=>'Sunglir', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Rainbow runner', :lat_nm => 'Elagatis bipinnulatus (Quoy & Gaimard, 1824)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.015', :nat_nm=>'Tetengkek', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Torpedo scad', :lat_nm => 'Megalaspis cordyla (Linnaeus, 1758)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.016', :nat_nm=>'Talang-talang', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Talang queenfish', :lat_nm => 'Scomberoides commersonnianus (Lacepède, 1802)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.017', :nat_nm=>'Talang-talang', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Needlescale queenfish', :lat_nm => 'Scomberoides tol (Cuvier, 1832)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.018', :nat_nm=>'Bentong', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Oxeye scad', :lat_nm => 'Selar boops (Valenciennes, 1833)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.019', :nat_nm=>'Bentong', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Bigeye scad', :lat_nm => 'Selar crumenophthalmus (Bloch, 1793)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.020', :nat_nm=>'Selar kuning', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Yellowstripe scad', :lat_nm => 'Selaroides leptolepis (Cuvier, 1833)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.021', :nat_nm=>'Selar kuning', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'Black banded trevally', :lat_nm => 'Seriolina nigrofasciata (Rüppell, 1829)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.022', :nat_nm=>'Selar kuning', :loc_nm => '', :family => 'Carangidae', :eng_nm => 'White mouth jack', :lat_nm => 'Uraspis uraspis', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.023', :nat_nm=>'Kakap putih', :loc_nm => '', :family => 'Centropomidae', :eng_nm => 'Barramundi, Giant sea perch', :lat_nm => 'Lates calcarifer (Bloch)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.024', :nat_nm=>'Golok-golok', :loc_nm => '', :family => 'Chirocentridae', :eng_nm => 'Dorab wolf-herring', :lat_nm => 'Chirocentrus dorab (Forsskål, 1775)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.025', :nat_nm=>'Selanget', :loc_nm => '', :family => 'Clupeidae', :eng_nm => 'Chacunda gizard shad', :lat_nm => 'Anodonstoma chacunda (Hamilton-Buchanan,1822)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.026', :nat_nm=>'Siro', :loc_nm => '', :family => 'Clupeidae', :eng_nm => 'Spotted sardinella', :lat_nm => 'Amblygaster sirm (Walbaum, 1792)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.027', :nat_nm=>'Japuh', :loc_nm => '', :family => 'Clupeidae', :eng_nm => 'Rainbow sardine', :lat_nm => 'Dussumieria acuta (Valenciennes, 1847)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.028', :nat_nm=>'Tembang', :loc_nm => '', :family => 'Clupeidae', :eng_nm => 'Deepbody sardinella', :lat_nm => 'Sardinella brachysoma (Bleeker, 1852)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.029', :nat_nm=>'Tembang', :loc_nm => '', :family => 'Clupeidae', :eng_nm => 'Fringescale sardinella', :lat_nm => 'Sardinella fimbriata (Valenciennes, 1847)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.030', :nat_nm=>'Tembang', :loc_nm => '', :family => 'Clupeidae', :eng_nm => 'Goldstripe sardinella', :lat_nm => 'Sardinella gibbosa (Bleeker, 1849)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.031', :nat_nm=>'Lemuru', :loc_nm => '', :family => 'Clupeidae', :eng_nm => 'Bali sardinella', :lat_nm => 'Sardinella lemuru (Bleeker, 1853)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.032', :nat_nm=>'Terubuk', :loc_nm => '', :family => 'Clupeidae', :eng_nm => 'Hilsha shad', :lat_nm => 'Tenualosa ilisha (Hamilton-Buchanan,1822)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.033', :nat_nm=>'Terubuk (dewasa), Pias (yuwana)', :loc_nm => '', :family => 'Clupeidae', :eng_nm => 'Longtail shad', :lat_nm => 'Tenualosa macrura (Bleeker, 1852)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.034', :nat_nm=>'Lemadang', :loc_nm => '', :family => 'Coryphaenidae', :eng_nm => 'Common dolphin fish', :lat_nm => 'Coryphaena hippurus (Linnaeus, 1758)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.035', :nat_nm=>'Beloso/Buntut kerbo', :loc_nm => '', :family => 'Cynodontidae', :eng_nm => 'Greater lizardfish', :lat_nm => 'Saurida tumbil  (Bloch, 1795)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.036', :nat_nm=>'Ikan lidah', :loc_nm => '', :family => 'Cynoglossidae', :eng_nm => 'Tongue soles', :lat_nm => 'Cynoglossus spp, Pleuronectus spp.', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.037', :nat_nm=>'Teri', :loc_nm => '', :family => 'Engraulidae', :eng_nm => 'Anchovies', :lat_nm => 'Stolephorus spp.', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.038', :nat_nm=>'Ikan terbang', :loc_nm => '', :family => 'Exocoitidae', :eng_nm => 'Flying fish', :lat_nm => 'Cypselurus spp.', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.039', :nat_nm=>'Bawal hitam', :loc_nm => '', :family => 'Formmionidae', :eng_nm => 'Black pomfret', :lat_nm => 'Formio niger (Bloch, 1795)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.040', :nat_nm=>'Julung-julung', :loc_nm => '', :family => 'Hemirhampidae', :eng_nm => 'Garfish and Halfbeaks', :lat_nm => 'Hemirhampus spp.', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.041', :nat_nm=>'Gerot-gerot', :loc_nm => '', :family => 'Haemulidae', :eng_nm => 'Saddle grunt/ Spotted javelinfish', :lat_nm => 'Pomadasys maculatus (Bloch, 1797)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.042', :nat_nm=>'Ikan Gaji', :loc_nm => '', :family => 'Haemulidae', :eng_nm => 'Sweetlips', :lat_nm => 'Plectorhinchus spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.043', :nat_nm=>'Ikan nomei/Lomei', :loc_nm => '', :family => 'Harpadontidae', :eng_nm => 'Bombay duck', :lat_nm => 'Harpadon nehereus', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.044', :nat_nm=>'Ikan layaran, Jangilus', :loc_nm => '', :family => 'Istiophoridae', :eng_nm => 'Indo-Pacific sailfish', :lat_nm => 'Istiophorus platypterus (Shaw and Nodder, 1792)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.045', :nat_nm=>'Setuhuk hitam', :loc_nm => '', :family => 'Istiophoridae', :eng_nm => 'Black marlin', :lat_nm => 'Makaira indica (Cuvier, 1832)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.046', :nat_nm=>'Setuhuk biru', :loc_nm => '', :family => 'Istiophoridae', :eng_nm => 'Indo-Pacific blue marlin', :lat_nm => 'Makaira mazarra (Jordan & Sneyder, 1901)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.047', :nat_nm=>'Setuhuk loreng', :loc_nm => '', :family => 'Istiophoridae', :eng_nm => 'Stripped marlin', :lat_nm => 'Tetrapturus audax (Philippi, 1887)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.048', :nat_nm=>'Ikan pedang', :loc_nm => '', :family => 'Istiophoridae', :eng_nm => 'Swordfish', :lat_nm => 'Xiphias gladius (Linnaeus, 1758)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.049', :nat_nm=>'Ikan napoleon', :loc_nm => '', :family => 'Labridae', :eng_nm => 'Napoleon wrasse/ Humhead wrasse', :lat_nm => 'Cheilinus undulatus', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.050', :nat_nm=>'Kapas-kapas', :loc_nm => '', :family => 'Lactariidae', :eng_nm => 'Fals trevally', :lat_nm => 'Lactarius lactarius (Bloch & Schneider, 1801)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.051', :nat_nm=>'Peperek', :loc_nm => '', :family => 'Leiognathidae', :eng_nm => 'Slipmouths or Pony fishes', :lat_nm => 'Leiognathus spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.052', :nat_nm=>'Lencam', :loc_nm => '', :family => 'Lethrinidae', :eng_nm => 'Emperors', :lat_nm => 'Lethrinus spp.', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.053', :nat_nm=>'Ikan kakap merah/Bambangan', :loc_nm => '', :family => 'Lutjanidae', :eng_nm => 'Red snappers', :lat_nm => 'Lutjanus spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.054', :nat_nm=>'Pinjalo', :loc_nm => '', :family => 'Lutjanidae', :eng_nm => 'Goldenbanded jobfish', :lat_nm => 'Pristipomoides multidens (Day, 1870)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.055', :nat_nm=>'Pinjalo', :loc_nm => '', :family => 'Lutjanidae', :eng_nm => 'Sharptooth jobfish', :lat_nm => 'Pristipomoides typus (Bleeker, 1852)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.056', :nat_nm=>'Belanak', :loc_nm => '', :family => 'Mugillidae', :eng_nm => 'Mangrove mullets', :lat_nm => 'Mugil cephalus (Linnaeus, 1758)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.057', :nat_nm=>'Belanak', :loc_nm => '', :family => 'Mugillidae', :eng_nm => 'Blue-spot mullet/ Blue-tail mullet', :lat_nm => 'Valamugil seheli (Forsskål, 1775)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.058', :nat_nm=>'Biji nangka karang', :loc_nm => '', :family => 'Mullidae', :eng_nm => 'Indian goatfish', :lat_nm => 'Parupeneus indicus (Shaw, 1803)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.059', :nat_nm=>'Kuniran', :loc_nm => '', :family => 'Mullidae', :eng_nm => 'Sulphur goatfish', :lat_nm => 'Upeneus sulphureus  (Cuvier, 1829)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.060', :nat_nm=>'Biji nangka', :loc_nm => '', :family => 'Mullidae', :eng_nm => 'Yellow-stripe goatfish', :lat_nm => 'Upeneus vittatus (Forsskål, 1775)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.061', :nat_nm=>'Kurisi', :loc_nm => '', :family => 'Nemipteridae', :eng_nm => 'Ornate threadfin bream', :lat_nm => 'Nemimterus hexodon (Qouy & Gaimard, 1824)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.062', :nat_nm=>'Ikan sebelah mata kiri', :loc_nm => '', :family => 'Paralichthyidae', :eng_nm => 'Short pelvic flounders', :lat_nm => 'Paralichthyidae (Pseudorhombus Arsius)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.063', :nat_nm=>'Ikan sebelah mata kanan', :loc_nm => '', :family => 'Pleuronectidae', :eng_nm => 'Right handed flounders', :lat_nm => 'Pleuronectidae (Poecilopsetta colorata)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.064', :nat_nm=>'Kurau', :loc_nm => '', :family => 'Polynemidae', :eng_nm => 'Four finger threadfin', :lat_nm => 'Eleutheronema tetradactylum (Shaw, 1804)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.065', :nat_nm=>'Kuro/senangin', :loc_nm => '', :family => 'Polynemidae', :eng_nm => 'Threadfins', :lat_nm => 'Polynemus spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.066', :nat_nm=>'Serinding tembakau', :loc_nm => '', :family => 'Priacanthidae', :eng_nm => 'Red bigeye', :lat_nm => 'Priacanthus marcracanthus (Cuvier, 1829)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.067', :nat_nm=>'Swanggi', :loc_nm => '', :family => 'Priacanthidae', :eng_nm => 'Purple-spotted bigeye', :lat_nm => 'Priacanthus tayenus (Richardson, 1846)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.068', :nat_nm=>'Ikan sebelah (Terompa)', :loc_nm => '', :family => 'Psettodidae', :eng_nm => 'Indian halibut/ Queensland halibut', :lat_nm => 'Psettodes erumei (Schneider, 1801)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.069', :nat_nm=>'Gulamah/Tigawaja', :loc_nm => '', :family => 'Sciaenidae', :eng_nm => 'Croackers', :lat_nm => 'Nibea albiflora (Ricahardson, 1846)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.070', :nat_nm=>'Lisong', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Bullet tuna', :lat_nm => 'Auxis rochei (Risso, 1810)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.071', :nat_nm=>'Tongkol krai', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Frigate tuna', :lat_nm => 'Auxis thazard (Lacepède, 1800)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.072', :nat_nm=>'Tongkol como', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Kawa-kawa/ Eastern little tuna', :lat_nm => 'Euthynnus affinis (Cantor, 1849)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.073', :nat_nm=>'Cakalang', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Skipjack tuna', :lat_nm => 'Katsuwonus pelamis (Linnaeus, 1758)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.074', :nat_nm=>'Kembung', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Short-bodied mackerel', :lat_nm => 'Rastrelliger brachysoma', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.075', :nat_nm=>'Banyar', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Indian mackerel', :lat_nm => 'Rastrelliger kanagurta', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.076', :nat_nm=>'Kenyar', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Striped bonito', :lat_nm => 'Sarda orientalis (Temminck & Schlegel, 1844)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.077', :nat_nm=>'Slengseng', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Spotted chub mackerel', :lat_nm => 'Scomber australasicus (Cuvier, 1831)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.078', :nat_nm=>'Tenggiri', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Narrow-barred Spanish mackerel', :lat_nm => 'Scomberomorus commerson (Lacepède, 1800)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.079', :nat_nm=>'Tenggiri papan', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Indo-Pacific king mackerel', :lat_nm => 'Scomberomorus guttatus (Bloch & Schneider, 1801)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.080', :nat_nm=>'Albakora', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Albacore', :lat_nm => 'Thunnus alalunga (Bonnaterre, 1788)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.081', :nat_nm=>'Madidihang', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Yellowfin tuna', :lat_nm => 'Thunnus albacares (Bonnaterre, 1788)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.082', :nat_nm=>'Tuna sirip biru selatan', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Sothern bluefin tuna', :lat_nm => 'Thunnus maccoyii (Castelnau, 1872)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.083', :nat_nm=>'Tuna mata besar', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Bigeye tuna', :lat_nm => 'Thunnus Obesus (Lowe, 1839)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.084', :nat_nm=>'Tongkol abu-abu', :loc_nm => '', :family => 'Scombridae', :eng_nm => 'Longtail tuna', :lat_nm => 'Thunnus tonggol (Bleeker, 1851)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.085', :nat_nm=>'Kerapu karang', :loc_nm => '', :family => 'Serranidae', :eng_nm => 'Blue-lined seabass', :lat_nm => 'Cephalophodis boenack (Bloch, 1790)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.086', :nat_nm=>'Kerapu bebek', :loc_nm => '', :family => 'Serranidae', :eng_nm => 'Humpback hind', :lat_nm => 'Cromileptes altivelis (Valenciennes, 1828)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.087', :nat_nm=>'Kerapu balong', :loc_nm => '', :family => 'Serranidae', :eng_nm => 'Honeycomb grouper', :lat_nm => 'Epinephelus merra (Bloch, 1793)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.088', :nat_nm=>'Kerapu lumpur', :loc_nm => '', :family => 'Serranidae', :eng_nm => 'Greasy rockcod/ estuary rockcod', :lat_nm => 'Epinephelus tauvina', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.089', :nat_nm=>'Kerapu sunu', :loc_nm => '', :family => 'Serranidae', :eng_nm => 'Leopard coralgrouper', :lat_nm => 'Plectropomus leopardus (Lacepède, 1802)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.090', :nat_nm=>'Beronang lingkis', :loc_nm => '', :family => 'Siganidae', :eng_nm => 'White-spotted spinefoot', :lat_nm => 'Siganus canaliculatus (Park, 1797)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.091', :nat_nm=>'Ikan beronang', :loc_nm => '', :family => 'Siganidae', :eng_nm => 'Orange-spotted spinefoot', :lat_nm => 'Siganus guttatus (Bloch, 1787)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.092', :nat_nm=>'Beronang kuning', :loc_nm => '', :family => 'Siganidae', :eng_nm => 'Barhed spinefoot', :lat_nm => 'Siganus virgatus (Valenciennes, 1835)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.093', :nat_nm=>'Rejung', :loc_nm => '', :family => 'Sillaginidae', :eng_nm => 'Silver sillago', :lat_nm => 'Silago sihama (Forsskål, 1775)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.094', :nat_nm=>'Alu-alu/ Manggilala/Pucul', :loc_nm => '', :family => 'Sphyraenidae', :eng_nm => 'Great barracuda', :lat_nm => 'Sphyraena barracuda (Walbaum, 1792)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.095', :nat_nm=>'Senuk', :loc_nm => '', :family => 'Sphyraenidae', :eng_nm => 'Pickhandle barracuda', :lat_nm => 'Sphyraena jello (Cuvier, 1829)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.096', :nat_nm=>'Bawal putih', :loc_nm => '', :family => 'Stromateidae', :eng_nm => 'Silver pomfret', :lat_nm => 'Pampus argenteus (Euphrasen, 1788)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.097', :nat_nm=>'Kerong-kerong', :loc_nm => '', :family => 'Teraponidae', :eng_nm => 'Jarbua terapon', :lat_nm => 'Terapon jarbua  (Forsskål, 1775)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.098', :nat_nm=>'Kerong-kerong', :loc_nm => '', :family => 'Teraponidae', :eng_nm => 'Largescale terapon', :lat_nm => 'Terapon theraps (Cuvier, 1829)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.099', :nat_nm=>'Layur', :loc_nm => '', :family => 'Trichiuridae', :eng_nm => 'Hairtails', :lat_nm => 'Trichiurus spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.100', :nat_nm=>'Cucut tikus, Cucut monyet', :loc_nm => '', :family => 'Alopiidae', :eng_nm => 'Thresher sharks', :lat_nm => 'Alopias spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.101', :nat_nm=>'Cucut lanyam', :loc_nm => '', :family => 'Carcharhinidae', :eng_nm => 'Requiem sharks (ground sharks, blue sharks, sharpnose sharks)', :lat_nm => 'Carcharhinus spp.', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.102', :nat_nm=>'Mako', :loc_nm => '', :family => 'Lamnidae', :eng_nm => 'Mackerel sharks, Makos, White sharks, Porbeagles', :lat_nm => 'Isurus spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.103', :nat_nm=>'Ikan gergaji', :loc_nm => '', :family => 'Pristidae', :eng_nm => 'Sawfishes', :lat_nm => 'Pristis spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.104', :nat_nm=>'Cucut martil, Capingan', :loc_nm => '', :family => 'Sphyrnidae', :eng_nm => 'Wingehead, Hammerhead sharks', :lat_nm => 'Eusphyra blochi (Cuvier, 1816) Sphyma spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.105', :nat_nm=>'Cucut botol', :loc_nm => '', :family => 'Squalidae', :eng_nm => 'Dogfish sharks', :lat_nm => 'Squalus spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.106', :nat_nm=>'Pari kembang, Pari macan', :loc_nm => '', :family => 'Dasyatidae', :eng_nm => 'Stingrays', :lat_nm => 'Dasyatis spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.107', :nat_nm=>'Pari kelelawar', :loc_nm => '', :family => 'Mobulidae', :eng_nm => 'Devilrays, Mantarays', :lat_nm => 'Mobula spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.108', :nat_nm=>'Pari burung', :loc_nm => '', :family => 'Myliobathidae', :eng_nm => 'Eaglerays', :lat_nm => 'Myliobatus spp, Aetobatus spp. (Euphrasen, 1790) Aetomylaeus spp', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.109', :nat_nm=>'Pari hidung sekop', :loc_nm => '', :family => 'Rhinidae', :eng_nm => 'Guitarfishes, Shovelnose rays', :lat_nm => 'Rhina ancylostoma (Bloch & Schneider, 1801)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL1.110', :nat_nm=>'Pari kekeh', :loc_nm => '', :family => 'Rhinidae', :eng_nm => 'Whitespotted wedgefishes', :lat_nm => 'Rhynchobatus djiddensis (Forsskal, 1775)', :sector_id =>31, :water_id =>21, :category_id =>11, :status_id =>41},
  #{:code=>'IPL1.999', :nat_nm=>'Ikan Laut Lainnya(-)', :loc_nm => '', :family => '', :eng_nm => '', :lat_nm => '', :sector_id =>, :water_id =>, :category_id =>, :status_id =>},
  {:code=>'IPL2.001', :nat_nm=>'Udang  Dogol', :loc_nm => '', :family => 'Penaeidae', :eng_nm => 'Endeavour prawn/ Shrimp blue tail endeavour prawn', :lat_nm => 'Metapenaeus endeavouri (Schmitt, 1926)', :sector_id =>32, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.002', :nat_nm=>'Udang  Dogol', :loc_nm => '', :family => 'Penaeidae', :eng_nm => 'Endeavour prawn/ Shrimp red greasiback', :lat_nm => 'Metapenaeus ensis, (de Haan, 1850), Metapenaeus monoceros, (Fabricius, 1798)', :sector_id =>32, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.003', :nat_nm=>'Udang  Jerbung,  Udang  putih', :loc_nm => '', :family => 'Penaeidae', :eng_nm => 'Banana prawn/ White shrimp', :lat_nm => 'Penaeus merguiensis (de Man, 1888 )', :sector_id =>32, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.004', :nat_nm=>'Udang  Jerbung,  Udang  putih', :loc_nm => '', :family => 'Penaeidae', :eng_nm => 'Banana prawn, Indian  banana', :lat_nm => 'Penaeus indicus (Milne Edwards, 1837)', :sector_id =>32, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.005', :nat_nm=>'Udang  krosok', :loc_nm => '', :family => 'Penaeidae', :eng_nm => 'Tiger cat shrimp,  Rainbow  shrimp', :lat_nm => 'Parapenaeopsis sculptitis (Heller, 1862)', :sector_id =>32, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.006', :nat_nm=>'Udang  ratu, Udang  raja', :loc_nm => '', :family => 'Penaeidae', :eng_nm => 'King  prawn , Blue legged, King prawn', :lat_nm => 'Penaeus latisulcatus  (Kishinouye, 1896)', :sector_id =>32, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.007', :nat_nm=>'Udang  windu', :loc_nm => '', :family => 'Penaeidae', :eng_nm => 'Jumbo tiger prawn/ shrimp, Giant tiger prawn/shrimp,  Blue  tiger  prawn', :lat_nm => 'Penaeus monodon (Fabricius, 1798)', :sector_id =>32, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.008', :nat_nm=>'Udang  Windu', :loc_nm => '', :family => 'Penaeidae', :eng_nm => 'Jumbo tiger prawn/ Brown  tiger prawn', :lat_nm => 'Penaeus semisulcatus (de Haan, 1850)', :sector_id =>32, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.009', :nat_nm=>'Udang  Windu', :loc_nm => '', :family => 'Penaeidae', :eng_nm => 'Tiger prawn/ Brown tiger prawn', :lat_nm => 'Penaeus esculentus (Haswell, 1879)', :sector_id =>32, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.010', :nat_nm=>'Udang  barong, Udang  karang', :loc_nm => '', :family => 'Polinuridae', :eng_nm => 'Spiny  lobsters', :lat_nm => 'Panulirus versicolor (Latreille, 1804)', :sector_id =>32, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.011', :nat_nm=>'Kepiting', :loc_nm => '', :family => 'Portunidae', :eng_nm => 'Mangrove/Mud crab.', :lat_nm => 'Scylla serrata (Forsskal, 1755)', :sector_id =>33, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.012', :nat_nm=>'Rajungan', :loc_nm => '', :family => 'Portunidae', :eng_nm => 'Swimming  Crabs', :lat_nm => 'Portunus  pelagicus (Linnaeus, 1766)', :sector_id =>33, :water_id =>21, :category_id =>11, :status_id =>41},
  #{:code=>'IPL2.013', :nat_nm=>'Udang Lainnya', :loc_nm => '', :family => '', :eng_nm => '', :lat_nm => '', :sector_id =>, :water_id =>, :category_id =>, :status_id =>},
  {:code=>'IPL2.014', :nat_nm=>'Penyu anjing, Penyu kepala besar Penyu kakaktua', :loc_nm => '', :family => 'Cheloniidae', :eng_nm => 'Loggerhead turtle', :lat_nm => 'Caretta caretta (Linneaus, 1758)', :sector_id =>33, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.015', :nat_nm=>'Penyu lumpur', :loc_nm => '', :family => 'Cheloniidae', :eng_nm => 'Olive ridley turtle', :lat_nm => 'Lepidochelys olivacea (Eschscholtz, 1829)', :sector_id =>33, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.016', :nat_nm=>'Penyu punggung rata', :loc_nm => '', :family => 'Cheloniidae', :eng_nm => 'Flatback turtle', :lat_nm => 'Natataor depressus', :sector_id =>33, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.017', :nat_nm=>'Penyu sisik', :loc_nm => '', :family => 'Cheloniidae', :eng_nm => 'Hawksbill turtle', :lat_nm => 'Eretmochelys imbricata (Linnaeus, 1776)', :sector_id =>33, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL2.018', :nat_nm=>'Penyu belimbing', :loc_nm => '', :family => 'Dermochelyidae', :eng_nm => 'Leatherback turtle', :lat_nm => 'Dermochelys coriacea (Vandelli, 1761)', :sector_id =>33, :water_id =>21, :category_id =>11, :status_id =>41},
  #{:code=>'IPL2.999', :nat_nm=>'Binatang Berkulit Keras Lainnya(-)', :loc_nm => '', :family => '', :eng_nm => '', :lat_nm => '', :sector_id =>, :water_id =>, :category_id =>, :status_id =>},
  {:code=>'IPL3.007', :nat_nm=>'Teripang', :loc_nm => '', :family => 'Holothuriidae', :eng_nm => 'Sea cucumbers', :lat_nm => 'Stichopus  spp', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL3.008', :nat_nm=>'Teripang gama', :loc_nm => '', :family => 'Holothuriidae', :eng_nm => 'Sea cucumber', :lat_nm => 'Stichopus variegatus (Selenka, 1867)', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL3.009', :nat_nm=>'Teripang kasur', :loc_nm => '', :family => 'Holothuriidae', :eng_nm => 'Brownish sea cucumber', :lat_nm => 'Mulleria lecanora (Jaeger, 1833)', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL3.010', :nat_nm=>'Teripang olok-olok', :loc_nm => '', :family => 'Holothuriidae', :eng_nm => 'Marmorate sea cucumber', :lat_nm => 'Holothuria  marmorata (Jaeger, 1833)', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL3.011', :nat_nm=>'Teripang pasir', :loc_nm => '', :family => 'Holothuriidae', :eng_nm => 'Sand sea cucumber', :lat_nm => 'Holothuria  scabra (Jaeger, 1833)', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL3.012', :nat_nm=>'Teripang petola', :loc_nm => '', :family => 'Holothuriidae', :eng_nm => 'White-spotted black sea cucumber', :lat_nm => 'Holothuria argus (Jaeger, 1833)', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  #{:code=>'IPL3.999', :nat_nm=>'Binatang Air Lainnya(-)', :loc_nm => '', :family => '', :eng_nm => '', :lat_nm => '', :sector_id =>, :water_id =>, :category_id =>, :status_id =>},
  {:code=>'IPL4.001', :nat_nm=>'Kerang darah', :loc_nm => '', :family => 'Arcidae', :eng_nm => 'Blood Cockles', :lat_nm => 'Anadara granosa (Linnaeus, 1758)', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL4.002', :nat_nm=>'Cumi-cumi', :loc_nm => '', :family => 'Loligonidae', :eng_nm => 'Common squids', :lat_nm => 'Loligo spp', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL4.003', :nat_nm=>'Kerang hijau', :loc_nm => '', :family => 'Mytilidae', :eng_nm => 'Green Mussel', :lat_nm => 'Perna viridis', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL4.004', :nat_nm=>'Gurita', :loc_nm => '', :family => 'Octopodidae', :eng_nm => 'Octopuses', :lat_nm => 'Octopus spp', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL4.005', :nat_nm=>'Tiram', :loc_nm => '', :family => 'Ostreidae', :eng_nm => 'Pacific oysters', :lat_nm => 'Crassostrea gigas (Thumberg)', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL4.006', :nat_nm=>'Simping', :loc_nm => '', :family => 'Pectinidae', :eng_nm => 'Scalops', :lat_nm => 'Amusium Spp', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL4.007', :nat_nm=>'Kerang mutiara', :loc_nm => '', :family => 'Pteriidae', :eng_nm => 'Golden (Yellow) Pearl Oyster (PO)', :lat_nm => 'Pinctada maxima (Jameson)', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL4.008', :nat_nm=>'Tapis-tapis, Kerang mutiara', :loc_nm => '', :family => 'Pteriidae', :eng_nm => 'Black-lip Pearl Oyster (PO)', :lat_nm => 'Pinctada margaritifera (Linne, 1758)', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL4.009', :nat_nm=>'Sotong', :loc_nm => '', :family => 'Sepiidae', :eng_nm => 'Cuttle – fish', :lat_nm => 'Sepia Spp', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL4.010', :nat_nm=>'Lola, Susubundar', :loc_nm => '', :family => 'Trochidae', :eng_nm => 'Top Shell', :lat_nm => 'Trochus (Teptus) niloticus (Linne, 1758)', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL4.011', :nat_nm=>'Remis', :loc_nm => '', :family => 'Veneridae', :eng_nm => 'Clams', :lat_nm => 'Meretrix spp', :sector_id =>34, :water_id =>21, :category_id =>11, :status_id =>41},
  #{:code=>'IPL4.999', :nat_nm=>'Binatang Lunak Lainnya(-)', :loc_nm => '', :family => '', :eng_nm => '', :lat_nm => '', :sector_id =>, :water_id =>, :category_id =>, :status_id =>},
  {:code=>'IPL5.001', :nat_nm=>'Bunga karang', :loc_nm => '', :family => 'Aulletidae', :eng_nm => 'Sponge', :lat_nm => 'Aulleta spp', :sector_id =>36, :water_id =>21, :category_id =>11, :status_id =>41},
  {:code=>'IPL5.002', :nat_nm=>'Ubur-ubur', :loc_nm => '', :family => 'Catostylidae', :eng_nm => 'Jelly fish', :lat_nm => 'Rhopilema spp', :sector_id =>35, :water_id =>21, :category_id =>11, :status_id =>41},
  #{:code=>'IPL5.999', :nat_nm=>'Binatang Laut Lainnya(-)', :loc_nm => '', :family => '', :eng_nm => '', :lat_nm => '', :sector_id =>, :water_id =>, :category_id =>, :status_id =>},
  {:code=>'IPL6.001', :nat_nm=>'Rumput laut', :loc_nm => '', :family => 'Singnathidae', :eng_nm => 'Sea weeds', :lat_nm => 'Euchema spp, Gracillia sppAetomylaeus spp', :sector_id =>'36', :water_id =>"21", :category_id =>11, :status_id =>41}
  ])
  
boatsize = BoatSize.create([
  {:name=>'Jukung'},
  {:name=>'Perahu Papan Kecil'},
  {:name=>'Perahu Papan Sedang'},
  {:name=>'Perahu Papan Besar'},
  {:name=>'Motor Tempel < 5 GT'},
  {:name=>'Motor Tempel 5 - 10 GT'},
  {:name=>'Motor Tempel 10 - 20 GT'},
  {:name=>'Motor Tempel 20 - 30 GT'},
  {:name=>'Motor Tempel >= 30 GT'},
  {:name=>'Kapal Motor < 5 GT'},
  {:name=>'Kapal Motor  5 - 10 GT'},
  {:name=>'Kapal Motor 10 - 20 GT'},
  {:name=>'Kapal Motor 20 - 30 GT'},
  {:name=>'Kapal Motor 30 - 50 GT'},
  {:name=>'Kapal Motor 50 - 100 GT'},
  {:name=>'Kapal Motor  100 - 200 GT'},
  {:name=>'Kapal Motor 200 - 300 GT'},
  {:name=>'Kapal Motor 300 - 500 GT'},
  {:name=>'Kapal Motor 500 - 1000 GT'},
  {:name=>'Kapal Motor >= 1000 GT'},
  {:name=>'Tanpa Perahu'}
  ])
  
province = Province.create([
  {:name=>'Prov. Nanggroe Aceh Darussalam'},
  {:name=>'Prov. Sumatera Utara'},
  {:name=>'Prov. Sumatera Barat'},
  {:name=>'Prov. Riau'},
  {:name=>'Prov. Jambi'},
  {:name=>'Prov. Sumatera Selatan'},
  {:name=>'Prov. Bengkulu'},
  {:name=>'Prov. Lampung'},
  {:name=>'Prov. Kep. Bangka Belitung'},
  {:name=>'Prov. Kepulauan Riau'},
  {:name=>'Prov. D K I  Jakarta'},
  {:name=>'Prov. Jawa Barat'},
  {:name=>'Prov. Jawa Tengah'},
  {:name=>'Prov. D I Yogyakarta'},
  {:name=>'Prov. Jawa Timur'},
  {:name=>'Prov. Banten'},
  {:name=>'Prov. Bali'},
  {:name=>'Prov. Nusa Tenggara Barat'},
  {:name=>'Prov. Nusa Tenggara Timur'},
  {:name=>'Prov. Kalimantan Barat'},
  {:name=>'Prov. Kalimantan Tengah'},
  {:name=>'Prov. Kalimantan Selatan'},
  {:name=>'Prov. Kalimantan Timur'},
  {:name=>'Prov. Sulawesi Utara'},
  {:name=>'Prov. Sulawesi Tengah'},
  {:name=>'Prov. Sulawesi Selatan'},
  {:name=>'Prov. Sulawesi Tenggara'},
  {:name=>'Prov. Gorontalo'},
  {:name=>'Prov. Sulawesi Barat'},
  {:name=>'Prov. Maluku'},
  {:name=>'Prov. Maluku  Utara'},
  {:name=>'Prov. Irian Jaya Barat'},
  {:name=>'Prov. Papua'}
  ])
  
district = District.create([
  {:name=>'Kab. Simeulue',	:province_id=>11},
  {:name=>'Kab. Aceh Singkil',	:province_id=>11},
  {:name=>'Kab. Aceh Selatan',	:province_id=>11},
  {:name=>'Kab. Aceh Tenggara',	:province_id=>11},
  {:name=>'Kab. Aceh Timur',	:province_id=>11},
  {:name=>'Kab. Aceh Tengah',	:province_id=>11},
  {:name=>'Kab. Aceh Barat',	:province_id=>11},
  {:name=>'Kab. Aceh Besar',	:province_id=>11},
  {:name=>'Kab. Pidie',	:province_id=>11},
  {:name=>'Kab. Bireuen',	:province_id=>11},
  {:name=>'Kab. Aceh Utara',	:province_id=>11},
  {:name=>'Kab. Aceh Barat Daya',	:province_id=>11},
  {:name=>'Kab. Gayo Lues',	:province_id=>11},
  {:name=>'Kab. Aceh Tamiang',	:province_id=>11},
  {:name=>'Kab. Nagan Raya',	:province_id=>11},
  {:name=>'Kab. Aceh Jaya',	:province_id=>11},
  {:name=>'Kab. Bener Meriah',	:province_id=>11},
  {:name=>'Kota Banda Aceh',	:province_id=>11},
  {:name=>'Kota Sabang',	:province_id=>11},
  {:name=>'Kota Langsa',	:province_id=>11},
  {:name=>'Kota Lhokseumawe',	:province_id=>11},
  {:name=>'Kab. Nias',	:province_id=>12},
  {:name=>'Kab. Mandailing Natal',	:province_id=>12},
  {:name=>'Kab. Tapanuli Selatan',	:province_id=>12},
  {:name=>'Kab. Tapanuli Tengah',	:province_id=>12},
  {:name=>'Kab. Tapanuli Utara',	:province_id=>12},
  {:name=>'Kab. Toba Samosir',	:province_id=>12},
  {:name=>'Kab. Labuhan Batu',	:province_id=>12},
  {:name=>'Kab. Asahan',	:province_id=>12},
  {:name=>'Kab. Simalungun',	:province_id=>12},
  {:name=>'Kab. Dairi',	:province_id=>12},
  {:name=>'Kab. Karo',	:province_id=>12},
  {:name=>'Kab. Deli Serdang',	:province_id=>12},
  {:name=>'Kab. Langkat',	:province_id=>12},
  {:name=>'Kab. Nias Selatan',	:province_id=>12},
  {:name=>'Kab. Humbang Hasundutan',	:province_id=>12},
  {:name=>'Kab. Pakpak Barat',	:province_id=>12},
  {:name=>'Kab. Samosir',	:province_id=>12},
  {:name=>'Kab. Serdang Bedagai',	:province_id=>12},
  {:name=>'Kota Sibolga',	:province_id=>12},
  {:name=>'Kota Tanjung Balai',	:province_id=>12},
  {:name=>'Kota Pematang Siantar',	:province_id=>12},
  {:name=>'Kota Tebing Tinggi',	:province_id=>12},
  {:name=>'Kota Medan',	:province_id=>12},
  {:name=>'Kota Binjai',	:province_id=>12},
  {:name=>'Kota Padang Sidempuan',	:province_id=>12},
  {:name=>'Kab. Kepulauan Mentawai',	:province_id=>13},
  {:name=>'Kab. Pesisir Selatan',	:province_id=>13},
  {:name=>'Kab. Solok',	:province_id=>13},
  {:name=>'Kab. Sawahlunto/Sijunjung',	:province_id=>13},
  {:name=>'Kab. Tanah Datar',	:province_id=>13},
  {:name=>'Kab. Padang Pariaman',	:province_id=>13},
  {:name=>'Kab. Agam',	:province_id=>13},
  {:name=>'Kab. Lima Puluh Koto',	:province_id=>13},
  {:name=>'Kab. Pasaman',	:province_id=>13},
  {:name=>'Kab. Solok Selatan',	:province_id=>13},
  {:name=>'Kab. Dharmas Raya',	:province_id=>13},
  {:name=>'Kab. Pasaman Barat',	:province_id=>13},
  {:name=>'Kota Padang',	:province_id=>13},
  {:name=>'Kota Solok',	:province_id=>13},
  {:name=>'Kota Sawah Lunto',	:province_id=>13},
  {:name=>'Kota Padang Panjang',	:province_id=>13},
  {:name=>'Kota Bukittinggi',	:province_id=>13},
  {:name=>'Kota Payakumbuh',	:province_id=>13},
  {:name=>'Kota Pariaman',	:province_id=>13},
  {:name=>'Kab. Kuantan Singingi',	:province_id=>14},
  {:name=>'Kab. Indragiri Hulu',	:province_id=>14},
  {:name=>'Kab. Indragiri Hilir',	:province_id=>14},
  {:name=>'Kab. Pelalawan',	:province_id=>14},
  {:name=>'Kab. Siak',	:province_id=>14},
  {:name=>'Kab. Kampar',	:province_id=>14},
  {:name=>'Kab. Rokan Hulu',	:province_id=>14},
  {:name=>'Kab. Bengkalis',	:province_id=>14},
  {:name=>'Kab. Rokan Hilir',	:province_id=>14},
  {:name=>'Kota Pekan Baru',	:province_id=>14},
  {:name=>'Kota Dumai',	:province_id=>14},
  {:name=>'Kab. Kerinci',	:province_id=>15},
  {:name=>'Kab. Merangin',	:province_id=>15},
  {:name=>'Kab. Sarolangun ',	:province_id=>15},
  {:name=>'Kab. Batang Hari',	:province_id=>15},
  {:name=>'Kab. Muaro Jambi',	:province_id=>15},
  {:name=>'Kab. Tanjung Jabung Timur',	:province_id=>15},
  {:name=>'Kab. Tanjung Jabung Barat',	:province_id=>15},
  {:name=>'Kab. Tebo',	:province_id=>15},
  {:name=>'Kab. Bungo ',	:province_id=>15},
  {:name=>'Kota Jambi',	:province_id=>15},
  {:name=>'Kab. Ogan Komering Ulu',	:province_id=>16},
  {:name=>'Kab. Ogan Komering Ilir',	:province_id=>16},
  {:name=>'Kab. Muara Enim',	:province_id=>16},
  {:name=>'Kab. Lahat',	:province_id=>16},
  {:name=>'Kab. Musi Rawas',	:province_id=>16},
  {:name=>'Kab. Musi Banyuasin',	:province_id=>16},
  {:name=>'Kab. Banyuasin',	:province_id=>16},
  {:name=>'Kab. Ogan Komering Ulu Selatan',	:province_id=>16},
  {:name=>'Kab. Ogan Komering Ulu Timur',	:province_id=>16},
  {:name=>'Kab. Ogan Ilir',	:province_id=>16},
  {:name=>'Kota Palembang',	:province_id=>16},
  {:name=>'Kota Prabumulih',	:province_id=>16},
  {:name=>'Kota Pagar Alam',	:province_id=>16},
  {:name=>'Kota Lubuk Linggau',	:province_id=>16},
  {:name=>'Kab. Bengkulu Selatan',	:province_id=>17},
  {:name=>'Kab. Rejang Lebong',	:province_id=>17},
  {:name=>'Kab. Bengkulu Utara',	:province_id=>17},
  {:name=>'Kab. Kaur',	:province_id=>17},
  {:name=>'Kab. Seluma',	:province_id=>17},
  {:name=>'Kab. Mukomuko',	:province_id=>17},
  {:name=>'Kab. Lebong ',	:province_id=>17},
  {:name=>'Kab. Kepahiang',	:province_id=>17},
  {:name=>'Kota Bengkulu',	:province_id=>17},
  {:name=>'Kab. Lampung Barat',	:province_id=>18},
  {:name=>'Kab. Tanggamus',	:province_id=>18},
  {:name=>'Kab. Lampung Selatan',	:province_id=>18},
  {:name=>'Kab. Lampung Timur',	:province_id=>18},
  {:name=>'Kab. Lampung Tengah',	:province_id=>18},
  {:name=>'Kab. Lampung Utara',	:province_id=>18},
  {:name=>'Kab. Way Kanan',	:province_id=>18},
  {:name=>'Kab. Tulang Bawang',	:province_id=>18},
  {:name=>'Kota Bandar Lampung',	:province_id=>18},
  {:name=>'Kota Metro',	:province_id=>18},
  {:name=>'Kab. Bangka',	:province_id=>19},
  {:name=>'Kab. Belitung',	:province_id=>19},
  {:name=>'Kab. Bangka Barat',	:province_id=>19},
  {:name=>'Kab. Bangka Tengah',	:province_id=>19},
  {:name=>'Kab. Bangka Selatan',	:province_id=>19},
  {:name=>'Kab. Belitung Timur',	:province_id=>19},
  {:name=>'Kota Pangkal Pinang',	:province_id=>19},
  {:name=>'Kab. Karimun',	:province_id=>20},
  {:name=>'Kab. Bintan',	:province_id=>20},
  {:name=>'Kab. Natuna',	:province_id=>20},
  {:name=>'Kab. Lingga',	:province_id=>20},
  {:name=>'Kota Batam',	:province_id=>20},
  {:name=>'Kota Tanjung Pinang',	:province_id=>20},
  {:name=>'Kab. Adm. Kepulauan Seribu',	:province_id=>31},
  {:name=>'Kota Jakarta Selatan',	:province_id=>31},
  {:name=>'Kota Jakarta Timur',	:province_id=>31},
  {:name=>'Kota Jakarta Pusat',	:province_id=>31},
  {:name=>'Kota Jakarta Barat',	:province_id=>31},
  {:name=>'Kota Jakarta Utara',	:province_id=>31},
  {:name=>'Kab. Bogor',	:province_id=>32},
  {:name=>'Kab. Sukabumi',	:province_id=>32},
  {:name=>'Kab. Cianjur',	:province_id=>32},
  {:name=>'Kab. Bandung',	:province_id=>32},
  {:name=>'Kab. Garut',	:province_id=>32},
  {:name=>'Kab. Tasikmalaya',	:province_id=>32},
  {:name=>'Kab. Ciamis',	:province_id=>32},
  {:name=>'Kab. Kuningan',	:province_id=>32},
  {:name=>'Kab. Cirebon',	:province_id=>32},
  {:name=>'Kab. Majalengka',	:province_id=>32},
  {:name=>'Kab. Sumedang',	:province_id=>32},
  {:name=>'Kab. Indramayu',	:province_id=>32},
  {:name=>'Kab. Subang',	:province_id=>32},
  {:name=>'Kab. Purwakarta',	:province_id=>32},
  {:name=>'Kab. Karawang',	:province_id=>32},
  {:name=>'Kab. Bekasi',	:province_id=>32},
  {:name=>'Kota Bogor',	:province_id=>32},
  {:name=>'Kota Sukabumi',	:province_id=>32},
  {:name=>'Kota Bandung',	:province_id=>32},
  {:name=>'Kota Cirebon',	:province_id=>32},
  {:name=>'Kota Bekasi',	:province_id=>32},
  {:name=>'Kota Depok',	:province_id=>32},
  {:name=>'Kota Cimahi',	:province_id=>32},
  {:name=>'Kota Tasikmalaya',	:province_id=>32},
  {:name=>'Kota Banjar',	:province_id=>32},
  {:name=>'Kab. Cilacap',	:province_id=>33},
  {:name=>'Kab. Banyumas',	:province_id=>33},
  {:name=>'Kab. Purbalingga',	:province_id=>33},
  {:name=>'Kab. Banjarnegara',	:province_id=>33},
  {:name=>'Kab. Kebumen',	:province_id=>33},
  {:name=>'Kab. Purworejo',	:province_id=>33},
  {:name=>'Kab. Wonosobo',	:province_id=>33},
  {:name=>'Kab. Magelang',	:province_id=>33},
  {:name=>'Kab. Boyolali',	:province_id=>33},
  {:name=>'Kab. Klaten',	:province_id=>33},
  {:name=>'Kab. Sukoharjo',	:province_id=>33},
  {:name=>'Kab. Wonogiri',	:province_id=>33},
  {:name=>'Kab. Karanganyar',	:province_id=>33},
  {:name=>'Kab. Sragen',	:province_id=>33},
  {:name=>'Kab. Grobogan',	:province_id=>33},
  {:name=>'Kab. Blora',	:province_id=>33},
  {:name=>'Kab. Rembang',	:province_id=>33},
  {:name=>'Kab. Pati',	:province_id=>33},
  {:name=>'Kab. Kudus',	:province_id=>33},
  {:name=>'Kab. Jepara',	:province_id=>33},
  {:name=>'Kab. Demak',	:province_id=>33},
  {:name=>'Kab. Semarang',	:province_id=>33},
  {:name=>'Kab. Temanggung',	:province_id=>33},
  {:name=>'Kab. Kendal',	:province_id=>33},
  {:name=>'Kab. Batang',	:province_id=>33},
  {:name=>'Kab. Pekalongan',	:province_id=>33},
  {:name=>'Kab. Pemalang',	:province_id=>33},
  {:name=>'Kab. Tegal',	:province_id=>33},
  {:name=>'Kab. Brebes',	:province_id=>33},
  {:name=>'Kota Magelang',	:province_id=>33},
  {:name=>'Kota Surakarta',	:province_id=>33},
  {:name=>'Kota Salatiga',	:province_id=>33},
  {:name=>'Kota Semarang',	:province_id=>33},
  {:name=>'Kota Pekalongan',	:province_id=>33},
  {:name=>'Kota Tegal',	:province_id=>33},
  {:name=>'Kab. Kulon Progo',	:province_id=>34},
  {:name=>'Kab. Bantul',	:province_id=>34},
  {:name=>'Kab. Gunung Kidul',	:province_id=>34},
  {:name=>'Kab. Sleman',	:province_id=>34},
  {:name=>'Kota Yogyakarta',	:province_id=>34},
  {:name=>'Kab. Pacitan',	:province_id=>35},
  {:name=>'Kab. Ponorogo',	:province_id=>35},
  {:name=>'Kab. Trenggalek',	:province_id=>35},
  {:name=>'Kab. Tulungagung',	:province_id=>35},
  {:name=>'Kab. Blitar',	:province_id=>35},
  {:name=>'Kab. Kediri',	:province_id=>35},
  {:name=>'Kab. Malang',	:province_id=>35},
  {:name=>'Kab. Lumajang',	:province_id=>35},
  {:name=>'Kab. Jember',	:province_id=>35},
  {:name=>'Kab. Banyuwangi',	:province_id=>35},
  {:name=>'Kab. Bondowoso',	:province_id=>35},
  {:name=>'Kab. Situbondo',	:province_id=>35},
  {:name=>'Kab. Probolinggo',	:province_id=>35},
  {:name=>'Kab. Pasuruan',	:province_id=>35},
  {:name=>'Kab. Sidoarjo',	:province_id=>35},
  {:name=>'Kab. Mojokerto',	:province_id=>35},
  {:name=>'Kab. Jombang',	:province_id=>35},
  {:name=>'Kab. Nganjuk',	:province_id=>35},
  {:name=>'Kab. Madiun',	:province_id=>35},
  {:name=>'Kab. Magetan',	:province_id=>35},
  {:name=>'Kab. Ngawi',	:province_id=>35},
  {:name=>'Kab. Bojonegoro',	:province_id=>35},
  {:name=>'Kab. Tuban',	:province_id=>35},
  {:name=>'Kab. Lamongan',	:province_id=>35},
  {:name=>'Kab. Gresik',	:province_id=>35},
  {:name=>'Kab. Bangkalan',	:province_id=>35},
  {:name=>'Kab. Sampang',	:province_id=>35},
  {:name=>'Kab. Pamekasan',	:province_id=>35},
  {:name=>'Kab. Sumenep',	:province_id=>35},
  {:name=>'Kota Kediri',	:province_id=>35},
  {:name=>'Kota Blitar',	:province_id=>35},
  {:name=>'Kota Malang',	:province_id=>35},
  {:name=>'Kota Probolinggo',	:province_id=>35},
  {:name=>'Kota Pasuruan',	:province_id=>35},
  {:name=>'Kota Mojokerto',	:province_id=>35},
  {:name=>'Kota Madiun',	:province_id=>35},
  {:name=>'Kota Surabaya',	:province_id=>35},
  {:name=>'Kota Batu',	:province_id=>35},
  {:name=>'Kab. Pandeglang',	:province_id=>36},
  {:name=>'Kab. Lebak',	:province_id=>36},
  {:name=>'Kab. Tangerang',	:province_id=>36},
  {:name=>'Kab. Serang',	:province_id=>36},
  {:name=>'Kota Tangerang',	:province_id=>36},
  {:name=>'Kota Cilegon',	:province_id=>36},
  {:name=>'Kab. Jembrana',	:province_id=>51},
  {:name=>'Kab. Tabanan',	:province_id=>51},
  {:name=>'Kab. Badung',	:province_id=>51},
  {:name=>'Kab. Gianyar',	:province_id=>51},
  {:name=>'Kab. Klungkung',	:province_id=>51},
  {:name=>'Kab. Bangli',	:province_id=>51},
  {:name=>'Kab. Karang Asem',	:province_id=>51},
  {:name=>'Kab. Buleleng',	:province_id=>51},
  {:name=>'Kota Denpasar',	:province_id=>51},
  {:name=>'Kab. Lombok Barat',	:province_id=>52},
  {:name=>'Kab. Lombok Tengah',	:province_id=>52},
  {:name=>'Kab. Lombok Timur',	:province_id=>52},
  {:name=>'Kab. Sumbawa',	:province_id=>52},
  {:name=>'Kab. Dompu',	:province_id=>52},
  {:name=>'Kab. Bima',	:province_id=>52},
  {:name=>'Kab. Sumbawa Barat',	:province_id=>52},
  {:name=>'Kota Mataram',	:province_id=>52},
  {:name=>'Kota Bima',	:province_id=>52},
  {:name=>'Kab. Sumba Barat',	:province_id=>53},
  {:name=>'Kab. Sumba Timur',	:province_id=>53},
  {:name=>'Kab. Kupang',	:province_id=>53},
  {:name=>'Kab. Timor Tengah Selatan',	:province_id=>53},
  {:name=>'Kab. Timor Tengah Utara',	:province_id=>53},
  {:name=>'Kab. Belu',	:province_id=>53},
  {:name=>'Kab. Alor',	:province_id=>53},
  {:name=>'Kab. Lembata',	:province_id=>53},
  {:name=>'Kab. Flores Timur',	:province_id=>53},
  {:name=>'Kab. Sikka',	:province_id=>53},
  {:name=>'Kab. Ende',	:province_id=>53},
  {:name=>'Kab. Ngada',	:province_id=>53},
  {:name=>'Kab. Manggarai',	:province_id=>53},
  {:name=>'Kab. Rote Ndao',	:province_id=>53},
  {:name=>'Kab. Manggarai Barat',	:province_id=>53},
  {:name=>'Kota Kupang',	:province_id=>53},
  {:name=>'Kab. Sambas',	:province_id=>61},
  {:name=>'Kab. Bengkayang',	:province_id=>61},
  {:name=>'Kab. Landak',	:province_id=>61},
  {:name=>'Kab. Pontianak',	:province_id=>61},
  {:name=>'Kab. Sanggau',	:province_id=>61},
  {:name=>'Kab. Ketapang',	:province_id=>61},
  {:name=>'Kab. Sintang',	:province_id=>61},
  {:name=>'Kab. Kapuas Hulu',	:province_id=>61},
  {:name=>'Kab. Sekadau',	:province_id=>61},
  {:name=>'Kab. Melawi',	:province_id=>61},
  {:name=>'Kota Pontianak',	:province_id=>61},
  {:name=>'Kota Singkawang',	:province_id=>61},
  {:name=>'Kab. Kotawaringin Barat',	:province_id=>62},
  {:name=>'Kab. Kotawaringin Timur',	:province_id=>62},
  {:name=>'Kab. Kapuas',	:province_id=>62},
  {:name=>'Kab. Barito Selatan',	:province_id=>62},
  {:name=>'Kab. Barito Utara',	:province_id=>62},
  {:name=>'Kab. Sukamara',	:province_id=>62},
  {:name=>'Kab. Lamandau',	:province_id=>62},
  {:name=>'Kab. Seruyan',	:province_id=>62},
  {:name=>'Kab. Katingan',	:province_id=>62},
  {:name=>'Kab. Pulang Pisau',	:province_id=>62},
  {:name=>'Kab. Gunung Mas',	:province_id=>62},
  {:name=>'Kab. Barito Timur',	:province_id=>62},
  {:name=>'Kab. Murung Raya',	:province_id=>62},
  {:name=>'Kota Palangka Raya',	:province_id=>62},
  {:name=>'Kab. Tanah Laut',	:province_id=>63},
  {:name=>'Kab. Kota Baru',	:province_id=>63},
  {:name=>'Kab. Banjar',	:province_id=>63},
  {:name=>'Kab. Barito Kuala',	:province_id=>63},
  {:name=>'Kab. Tapin',	:province_id=>63},
  {:name=>'Kab. Hulu Sungai Selatan',	:province_id=>63},
  {:name=>'Kab. Hulu Sungai Tengah',	:province_id=>63},
  {:name=>'Kab. Hulu Sungai Utara',	:province_id=>63},
  {:name=>'Kab. Tabalong',	:province_id=>63},
  {:name=>'Kab. Tanah Bumbu',	:province_id=>63},
  {:name=>'Kab. Balangan',	:province_id=>63},
  {:name=>'Kota Banjarmasin',	:province_id=>63},
  {:name=>'Kota Banjar Baru',	:province_id=>63},
  {:name=>'Kab. Pasir',	:province_id=>64},
  {:name=>'Kab. Kutai Barat',	:province_id=>64},
  {:name=>'Kab. Kutai',	:province_id=>64},
  {:name=>'Kab. Kutai Timur',	:province_id=>64},
  {:name=>'Kab. Berau',	:province_id=>64},
  {:name=>'Kab. Malinau',	:province_id=>64},
  {:name=>'Kab. Bulungan',	:province_id=>64},
  {:name=>'Kab. Nunukan',	:province_id=>64},
  {:name=>'Kab. Penajam Paser Utara',	:province_id=>64},
  {:name=>'Kota Balikpapan',	:province_id=>64},
  {:name=>'Kota Samarinda',	:province_id=>64},
  {:name=>'Kota Tarakan',	:province_id=>64},
  {:name=>'Kota Bontang',	:province_id=>64},
  {:name=>'Kab. Bolaang Mongondow',	:province_id=>71},
  {:name=>'Kab. Minahasa',	:province_id=>71},
  {:name=>'Kab. Sangihe Talaud',	:province_id=>71},
  {:name=>'Kab. Kepulauan Talaud',	:province_id=>71},
  {:name=>'Kab. Minahasa Selatan',	:province_id=>71},
  {:name=>'Kab. Minahasa Utara',	:province_id=>71},
  {:name=>'Kota Manado',	:province_id=>71},
  {:name=>'Kota Bitung',	:province_id=>71},
  {:name=>'Kota Tomohon',	:province_id=>71},
  {:name=>'Kab. Banggai Kepulauan',	:province_id=>72},
  {:name=>'Kab. Banggai',	:province_id=>72},
  {:name=>'Kab. Morowali',	:province_id=>72},
  {:name=>'Kab. Poso',	:province_id=>72},
  {:name=>'Kab. Donggala',	:province_id=>72},
  {:name=>'Kab. Toli-Toli',	:province_id=>72},
  {:name=>'Kab. Buol',	:province_id=>72},
  {:name=>'Kab. Parigi Moutong',	:province_id=>72},
  {:name=>'Kab. Tojo Una-Una',	:province_id=>72},
  {:name=>'Kota Palu',	:province_id=>72},
  {:name=>'Kab. Selayar',	:province_id=>73},
  {:name=>'Kab. Bulukumba',	:province_id=>73},
  {:name=>'Kab. Bantaeng',	:province_id=>73},
  {:name=>'Kab. Jeneponto',	:province_id=>73},
  {:name=>'Kab. Takalar',	:province_id=>73},
  {:name=>'Kab. Gowa',	:province_id=>73},
  {:name=>'Kab. Sinjai',	:province_id=>73},
  {:name=>'Kab. Maros',	:province_id=>73},
  {:name=>'Kab. Pangkajene Kepulauan',	:province_id=>73},
  {:name=>'Kab. Barru',	:province_id=>73},
  {:name=>'Kab. Bone',	:province_id=>73},
  {:name=>'Kab. Soppeng',	:province_id=>73},
  {:name=>'Kab. Wajo',	:province_id=>73},
  {:name=>'Kab. Sidenreng Rappang',	:province_id=>73},
  {:name=>'Kab. Pinrang',	:province_id=>73},
  {:name=>'Kab. Enrekang',	:province_id=>73},
  {:name=>'Kab. Luwu',	:province_id=>73},
  {:name=>'Kab. Tana Toraja',	:province_id=>73},
  {:name=>'Kab. Luwu Utara',	:province_id=>73},
  {:name=>'Kab. Luwu Timur',	:province_id=>73},
  {:name=>'Kota Makassar',	:province_id=>73},
  {:name=>'Kota Pare-Pare',	:province_id=>73},
  {:name=>'Kota Palopo',	:province_id=>73},
  {:name=>'Kab. Buton',	:province_id=>74},
  {:name=>'Kab. Muna',	:province_id=>74},
  {:name=>'Kab. Konawe ',	:province_id=>74},
  {:name=>'Kab. Kolaka',	:province_id=>74},
  {:name=>'Kab. Konawe Selatan',	:province_id=>74},
  {:name=>'Kab. Bombana',	:province_id=>74},
  {:name=>'Kab. Wakatobi',	:province_id=>74},
  {:name=>'Kab. Kolaka Utara',	:province_id=>74},
  {:name=>'Kota Kendari',	:province_id=>74},
  {:name=>'Kota Baubau',	:province_id=>74},
  {:name=>'Kab. Boalemo',	:province_id=>75},
  {:name=>'Kab. Gorontalo',	:province_id=>75},
  {:name=>'Kab. Pohuwato',	:province_id=>75},
  {:name=>'Kab. Bone Bolango',	:province_id=>75},
  {:name=>'Kota Gorontalo',	:province_id=>75},
  {:name=>'Kab. Majene',	:province_id=>76},
  {:name=>'Kab. Polewali Mamasa',	:province_id=>76},
  {:name=>'Kab. Mamasa',	:province_id=>76},
  {:name=>'Kab. Mamuju',	:province_id=>76},
  {:name=>'Kab. Mamuju Utara',	:province_id=>76},
  {:name=>'Kab. Maluku Tenggara Barat',	:province_id=>81},
  {:name=>'Kab. Maluku Tenggara',	:province_id=>81},
  {:name=>'Kab. Maluku Tengah',	:province_id=>81},
  {:name=>'Kab. Buru',	:province_id=>81},
  {:name=>'Kab. Kepulauan Aru',	:province_id=>81},
  {:name=>'Kab. Seram Bagian Barat',	:province_id=>81},
  {:name=>'Kab. Seram Bagian Timur',	:province_id=>81},
  {:name=>'Kota Ambon',	:province_id=>81},
  {:name=>'Kab. Halmahera Barat',	:province_id=>82},
  {:name=>'Kab. Halmahera Tengah',	:province_id=>82},
  {:name=>'Kab. Kepulauan Sula',	:province_id=>82},
  {:name=>'Kab. Halmahera Selatan',	:province_id=>82},
  {:name=>'Kab. Halmahera Utara',	:province_id=>82},
  {:name=>'Kab. Halmahera Timur',	:province_id=>82},
  {:name=>'Kota Ternate',	:province_id=>82},
  {:name=>'Kota Tidore Kepulauan',	:province_id=>82},
  {:name=>'Kab. Fak-Fak',	:province_id=>91},
  {:name=>'Kab. Kaimana',	:province_id=>91},
  {:name=>'Kab. Teluk Wondama',	:province_id=>91},
  {:name=>'Kab. Teluk Bintuni',	:province_id=>91},
  {:name=>'Kab. Manokwari',	:province_id=>91},
  {:name=>'Kab. Sorong Selatan',	:province_id=>91},
  {:name=>'Kab. Sorong',	:province_id=>91},
  {:name=>'Kab. Raja Ampat',	:province_id=>91},
  {:name=>'Kota Sorong',	:province_id=>91},
  {:name=>'Kab. Merauke',	:province_id=>94},
  {:name=>'Kab. Jayawijaya',	:province_id=>94},
  {:name=>'Kab. Jayapura',	:province_id=>94},
  {:name=>'Kab. Nabire',	:province_id=>94},
  {:name=>'Kab. Yapen Waropen',	:province_id=>94},
  {:name=>'Kab. Biak Numfor',	:province_id=>94},
  {:name=>'Kab. Paniai',	:province_id=>94},
  {:name=>'Kab. Puncak Jaya',	:province_id=>94},
  {:name=>'Kab. Mimika',	:province_id=>94},
  {:name=>'Kab. Boven Digoel',	:province_id=>94},
  {:name=>'Kab. Mappi',	:province_id=>94},
  {:name=>'Kab. Asmat',	:province_id=>94},
  {:name=>'Kab. Yahukimo',	:province_id=>94},
  {:name=>'Kab. Pegunungan Bintang',	:province_id=>94},
  {:name=>'Kab. Tolikara',	:province_id=>94},
  {:name=>'Kab. Sarmi',	:province_id=>94},
  {:name=>'Kab. Keerom',	:province_id=>94},
  {:name=>'Kab. Waropen',	:province_id=>94},
  {:name=>'Kab. Supiori',	:province_id=>94},
  {:name=>'Kota Jayapura',	:province_id=>94},
  {:name=>'Kab. Gorontalo Utara',	:province_id=>75},
  {:name=>'Kab. Pulau Morotai',	:province_id=>82},
  {:name=>'Kab. Kepulauan Sitaro',	:province_id=>71},
  {:name=>'Kab. Minahasa Tenggara',	:province_id=>71},
  {:name=>'Kab. Bolaang Mongondow Utara',	:province_id=>71},
  {:name=>'Kab. Bolaang Mongondow Selatan',	:province_id=>71},
  {:name=>'Kab. Bolaang Mongondow Timur',	:province_id=>71},
  {:name=>'Kota Kotamobagu',	:province_id=>71},
  {:name=>'Kab. Buru Selatan',	:province_id=>81},
  {:name=>'Kab. Maluku Barat Daya',	:province_id=>81},
  {:name=>'Kota Tual',	:province_id=>81}
  ])
  
  